modLoader="javafml"
loaderVersion="[40,)"
license="ARR"

[[mods]]
modId="jadeaddons"
version="${file.jarVersion}"
displayName="Jade Addons"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/jade-addons"
description="Jade additional mod supports"

[[dependencies.jadeaddons]]
    modId="jade"
    mandatory=true
    versionRange="[5.2.3, )"
    ordering="NONE"
    side="BOTH"

[modproperties.jadeaddons]
    catalogueItemIcon="minecraft:spyglass" #Support for Catalogue mod
