modLoader = "javafml"
loaderVersion = "*"
license = "ARR"

[[mods]]
modId = "jadeaddons"
version = "${file.jarVersion}"
displayName = "Jade Addons"
authors = "Snownee"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/jade-addons"
description = "Jade additional mod supports"

[[dependencies.jadeaddons]]
modId = "jade"
type = "required"
versionRange = "[15.7.1, )"

[modproperties.jadeaddons]
catalogueItemIcon = "minecraft:spyglass" #Support for Catalogue mod
